# 1.预备知识

## 1.1数据操作

### 1.1.1创建数组


In [1]:
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

1.torch.arange(12)意思是：生成从 0 到 11 的连续整数。

2.什么是 Tensor？

  在 PyTorch 里，Tensor 可以粗暴理解成：
    
  专门给深度学习用的数组。

| 类型             | 用途            |
| -------------- | ------------- |
| Python list    | 普通存数据         |
| NumPy array    | 科学计算          |
| PyTorch Tensor | 深度学习、GPU、自动求导 |



查看形状：shape

In [2]:
x.shape

torch.Size([12])

查看元素总数

In [3]:
x.numel()

12

改变形状

In [4]:
x.reshape(2,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

接下来我们创建一个全零的，形状为（2,3,4）的张量

In [5]:
y=torch.zeros(2,3,4)
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

全一

In [6]:
z=torch.ones(2,3,4)
z

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

也可以通过python中的列表创建array，手动写数

In [7]:
w=torch.tensor([[1,2,3,4],
               [3,4,5,6],
               [4,5,6,6]])
w

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [4, 5, 6, 6]])

### 1.1.2运算

In [8]:
import torch
x=torch.arange(12)
x=x.reshape(3,4)
y=torch.tensor([[2,1,4,3],
                [1,2,3,4],
                [4,3,2,1]])
print(x)
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

1.X+Y(加法)

In [9]:
x+y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

2.对应的乘法

In [10]:
x*y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

3.除法

In [11]:
x/y

tensor([[ 0.0000,  1.0000,  0.5000,  1.0000],
        [ 4.0000,  2.5000,  2.0000,  1.7500],
        [ 2.0000,  3.0000,  5.0000, 11.0000]])

4.y的指数运算

In [12]:
y.exp()

tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

5.矩阵点乘

In [13]:
#pytorch写法
a=torch.matmul(x, y.T)
#python写法
b=x@y.T
print(a)
b

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])


tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

6.拼接

把 dim 理解成：沿着哪个方向把东西接起来。

（1）dim=0：让第 0 个维度变长

第 0 个维度是 行数。

（2）dim=1：让第 1 个维度变长

第 1 个维度是 列数。

In [14]:
torch.cat((x, y), dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [15]:
torch.cat((x, y), dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

在三维张量里，

假设有一个三维张量：

In [16]:
A = torch.zeros(2, 3, 4)

它的形状是：

In [17]:
A.shape
# torch.Size([2, 3, 4])

torch.Size([2, 3, 4])

理解成

2 个矩阵
每个矩阵 3 行
每行 4 列


即：
| 维度    | 代码      | 含义      |
| ----- | ------- | ------- |
| 第 1 维 | `dim=0` | 有几个矩阵   |
| 第 2 维 | `dim=1` | 每个矩阵有几行 |
| 第 3 维 | `dim=2` | 每行有几列   |


In [18]:
#设
B=torch.ones(2,3,4)
B

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
C1=torch.cat((A, B), dim=0)
C1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
C1.shape

torch.Size([4, 3, 4])

第一个数字变大：矩阵个数变多。

In [21]:
torch.cat((A, B), dim=1)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

第二个数字变大：每个矩阵的行数变多。

In [22]:
torch.cat((A, B), dim=2)

tensor([[[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]])

第三个数字变大：每行的列数变多。

7.判断每个量是否相等

In [23]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

8.元素之和
| 写法                | 结果类型                         |
| ----------------- | ---------------------------- |
| `X.sum()`         | PyTorch 张量：`tensor(66)`      |
| `X.sum().item()`  | Python 数字：`66`               |
| `X.norm()`        | PyTorch 张量：`tensor(22.4944)` |
| `X.norm().item()` | Python 数字：`22.4944...`       |


求和

In [24]:
x.sum()

tensor(66)

L2范数（平方和再开根号）

* 注意 ：torch.norm() 要求输入是 浮点数张量。

    Q：为什么 x.sum() 没问题？

    因为求和可以对整数做：

In [25]:
x.float().norm().item()

22.494443893432617

这里item把张量转化为标量

### 1.1.3 广播机制

当两个张量形状不同，但又要做逐元素运算时，PyTorch 会尝试自动扩展它们的形状，使它们可以运算。

In [26]:
import torch

A = torch.arange(3).reshape(3, 1)
B = torch.arange(2).reshape(1, 2)

A, B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

广播时：

* A 会被横向复制

A 原来：
[[0],

 [1],
 
 [2]]

A 广播后：
[[0, 0],
 
 [1, 1],
 
 [2, 2]]

* B 会被纵向复制：



然后逐元素相加：



In [27]:
A+B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

两个维度可以广播，必须满足下面条件之一

1. 两个维度相等

2. 其中一个维度是 1

例如：

(3, 4) + (1, 4) ✅

(3, 4) + (2, 4) ❌

### 1.1.4索引

索引=位置

1.范围截取：X[1:3]：取第 1 行到第 2 行（左闭右开原则）

取第 2 列到第 3 列
X[:, 1:3]

In [28]:
x[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [29]:
x[:, 1:3]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

2.x[1, 2] = 9：修改某一个元素

In [30]:
x[1, 2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

3.X[1:2, :] = 12：修改一整行

    1:2 → 取行索引 1，也就是第 2 行

    :   → 取所有列

In [31]:
x[1:2, :] = 12
x

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

* 二维张量访问格式:

    X[行, 列]

* 冒号 : 的意思

    例如：
    X[1, :]

    表示：
    第 2 行的所有列

    X[:, 2]

    表示：
    所有行的第 3 列

### 1.1.5运算的内存开销

我们对每个操作新开内存来存储运算结果 如Y=Y+X 会开新内存 并把新的Y指向新内存

这点我们可以用python自带的id函数验证，若id同 则地址同

In [32]:
Before=id(y)
y=y+4
id(y)==Before

False

pytorch这么写

In [33]:
import torch
before = id(y)
y = y + x
id(y) == before

False

* 为什么要关心这个？

    因为大张量很占内存。

    如果每次都新建一个张量，旧的还没释放，新的一直开，内存压力会变大。

方法 1：提前准备一个 Z，把结果写进去

(利用索引的替换操作把指定结果放到指定内存 先通过zero-like创建和y形状相同的tensor，记作z 再把X+Y的结果通过[:]写进z对应的内存中)

In [34]:
Z = torch.zeros_like(y)

before = id(Z)
Z[:] = x+ y

id(Z) == before

True

意思是：

Y = Y + X 会创建一个新的张量，然后让变量 Y 指向这个新张量。

也就是说，原来的 Y 没有被直接修改，而是换了一个新的对象。

方法 2：用 out=，更直接

PyTorch 写法：

In [35]:
Z = torch.zeros_like(y)

before = id(Z)
torch.add(x, y, out=Z)

id(Z) == before

True

意思是：

直接把 X + Y 的结果写进 Z，尽量避免额外创建结果张量

方法 3：直接原地改 X

如果后面不再需要旧的 X，可以写：

In [36]:
before = id(x)
x += y
id(x) == before

True

这表示：

X += Y 会直接在原来的 X 上修改。旧的 X 没了

* PyTorch 里很多带下划线的操作，比如 add_()，表示原地操作；官方文档也把 Tensor.add_() 定义为 add() 的 in-place 版本。

| 方法   | PyTorch 写法               |  是否换内存 | 是否推荐 | 含义                  |
| ---- | ------------------------ | -----: | ---- | ------------------- |
| 方法 1 | `Z[:] = X + Y`           | `Z` 不换 | 可以   | 先算出 `X + Y`，再写进 `Z` |
| 方法 2 | `torch.add(X, Y, out=Z)` | `Z` 不换 | 更好   | 直接把结果写进 `Z`，更省临时内存  |
| 方法 3 | `X += Y` 或 `X.add_(Y)`   | `X` 不换 | 谨慎   | 直接修改 `X` 本身         |



| 写法                       | 会不会新建变量对象 |     会不会覆盖原数据 | 适合场景           |
| ------------------------ | --------: | -----------: | -------------- |
| `Y = Y + X`              |         会 | 不覆盖旧数据，只是换引用 | 普通写法，最直观       |
| `Z[:] = X + Y`           |   不会换 `Z` |       覆盖 `Z` | 想把结果放进已有 `Z`   |
| `torch.add(X, Y, out=Z)` |   不会换 `Z` |       覆盖 `Z` | 更省内存地把结果写进 `Z` |
| `X += Y`                 |   不会换 `X` |       覆盖 `X` | 不再需要旧 `X` 时    |



### 1.1.6 PyTorch Tensor 和 NumPy 数组之间怎么互相转换

In [37]:
import torch
import numpy as np

P = np.ones((2, 3))
D = torch.tensor(P)
D

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

1. NumPy → PyTorch

* 方法一：torch.tensor(P)

    把 NumPy 数组 P 转成 PyTorch 张量 D。

* 方法二：torch.from_numpy(P)

In [38]:
D = torch.from_numpy(P)
D

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

2. PyTorch → NumPy

In [39]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

3. 重点：

    NumPy 用于普通科学计算，PyTorch Tensor 用于深度学习。两者可以互相转换。

In [40]:

torch.tensor(P)   # NumPy 转 TensorD.numpy()         

D.numpy() # Tensor 转 NumPy

print(D)

P

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


array([[1., 1., 1.],
       [1., 1., 1.]])

## 1.2自动求梯度

In [58]:
import torch

x = torch.arange(4.0).reshape(4, 1)
x.requires_grad_(True)

y = 2 * torch.matmul(x.T, x)

y.backward()

print(x.grad)

tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])


* “x = torch.arange(4.0).reshape(4, 1)”

  这里4.0
  因为求梯度要求浮点数张量。整数张量不能求梯度，PyTorch 文档也说明自动微分支持浮点和复数 Tensor。

x.requires_grad_(True)  意思是：

* 从现在开始，PyTorch 要记录和 x 有关的计算，后面准备对 x 求梯度。

y = 2 * torch.matmul(x.T, x)

* 不仅仅是算出来数 也记录了算出数的方式，方便后续的反向传播
* 一言概之：生成 y 和计算图

y.backward()

* 这句的意思是：

    从 y 开始，反向计算 y 对 x 的梯度。

* PyTorch 文档说明，backward() 会计算当前张量相对于计算图中叶子节点的梯度，并累积到这些张量的 .grad 属性里。

* y.backward计算 算完放x.grad里

* 注意：反向传播只能算一次，因为计算过程中，算完直接把原来的函数的信息“烧”掉了，以节省显存，要再次看就要重启kernel


### 1.2.1对python控制流求梯度

* 就算函数里面有 while、if 这种 Python 控制流，PyTorch 也能自动求梯度。

  因为 PyTorch 的 autograd 会在你实际执行代码时记录计算图，然后用链式法则反向求导；这个计算图是动态生成的，所以 Python 的条件判断、循环也能参与计算过程。



1. 先定义一个带控制流的函数


In [49]:
import torch

def f(a):
    b = a * 2
    
    while b.norm() < 1000:  #这里norm一般指L2范数
        b = b * 2
    
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    
    return c

这个函数里面有两个控制流：

* while 循环

* if 判断

In [59]:
a = torch.randn(1, requires_grad=True)

c = f(a)

c.backward()

a.grad

tensor([409600.])

2. 为什么能求导？

   每次真正运行时，PyTorch 都会记录实际发生过的计算。

   PyTorch 会记录这条实际路径。

   然后调用：

   c.backward()

   它就沿着这条路径反向求导。

3.验证

In [61]:
import torch

def f(a):
    b = a * 2
    
    while b.norm() < 1000:
        b = b * 2
    
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    
    return c


a = torch.randn(1, requires_grad=True)
c = f(a)

c.backward()

print("a =", a)
print("c =", c)
print("a.grad =", a.grad)
print("c / a =", c / a)
print(torch.allclose(a.grad, c / a))

a = tensor([-0.5922], requires_grad=True)
c = tensor([-121275.1953], grad_fn=<MulBackward0>)
a.grad = tensor([204800.])
c / a = tensor([204800.], grad_fn=<DivBackward0>)
True


* 解释

    a = torch.randn(1, requires_grad=True)

    生成一个随机数，并且告诉 PyTorch：

    我要对 a 求梯度。

    这里的 requires_grad=True 很关键。没有它，PyTorch 不会记录 a 后面的计算。官方文档也说，autograd 会追踪 requires_grad=True 的 Tensor 参与的操作。

7. 注意一个小坑

    如果你多次运行：
    c.backward()

    梯度会累加到：
    a.grad

    （例如）原来的 a.grad = 4
    这次又算出来 4
    累加后 = 8

    PyTorch 的 backward() 会把梯度累积到叶子张量的 .grad 里，所以训练时一般要先清零梯度。

    比如：a.grad.zero_()

    或者训练模型时常见：

    optimizer.zero_grad()

    否则梯度会越加越多，像你没清空购物车一样，越看越离谱。
* 正确做法：每次 backward 前先清零

In [69]:
import torch

a = torch.tensor(2.0, requires_grad=True)

c = a ** 2
c.backward()
print(a.grad)   # tensor(4.)

 # 无清空梯度

c = a ** 2
c.backward()
print(a.grad)   # tensor(4.)

tensor(4.)
tensor(8.)


In [70]:
import torch

a = torch.tensor(2.0, requires_grad=True)

c = a ** 2
c.backward()
print(a.grad)   # tensor(4.)

a.grad.zero_()  # 清空梯度

c = a ** 2
c.backward()
print(a.grad)   # tensor(4.)

tensor(4.)
tensor(4.)


8. 为什么要这样设计？

因为有些时候我们确实想累加梯度。

比如一个大 batch 太大，显存放不下，可以拆成几个小 batch：

小 batch 1 算一次梯度

小 batch 2 算一次梯度

小 batch 3 算一次梯度

最后一起更新参数

这叫 梯度累积 gradient accumulation。

所以 PyTorch 默认让梯度累加，不擅自清空。它不替你做主，像个冷漠但讲规矩的会计。

### 1.2.2 查阅文档

当你不知道 PyTorch 里有哪些函数、某个函数怎么用时，怎么自己查。

核心工具就三个：

dir()

help()

?


1. 查一个模块里有哪些函数：dir()

In [ ]:
import torch

print(dir(torch))

dir() 是 Python 内置函数，用来列出一个对象/模块里有哪些名字，比如函数、类、属性；Python 官方教程也把 dir() 和 help() 称为查看大型模块时很有用的交互辅助工具。

它会列出很多东西，比如：

tensor

arange

zeros

ones

randn

matmul

sum

mean

norm

...

这些都是 torch 里可以用的函数或对象。PyTorch 官方文档也说明，torch 包含多维张量的数据结构，并定义了大量张量数学运算

2. 查某个函数怎么用：help()

    如

In [73]:
help(torch.randn)

Help on built-in function randn in module torch:

randn(...)
    randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    For complex dtypes, the tensor is i.i.d. sampled from a `complex normal distribution`_ with zero mean and
    unit variance as
    
    .. math::
        \text{out}_{i} \sim \mathcal{CN}(0, 1)
    
    This is equivalent to separately sampling the real :math:`(\operatorname{Re})` and imaginary
    :math:`(\operatorname{Im})` part of :math:`\text{out}_i` as
    
    .. math::
        \operatorname{Re}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2}),\quad
        \operatorname{Im}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2})
    
    The shap

In [73]:
help(torch.randn)

Help on built-in function randn in module torch:

randn(...)
    randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    For complex dtypes, the tensor is i.i.d. sampled from a `complex normal distribution`_ with zero mean and
    unit variance as
    
    .. math::
        \text{out}_{i} \sim \mathcal{CN}(0, 1)
    
    This is equivalent to separately sampling the real :math:`(\operatorname{Re})` and imaginary
    :math:`(\operatorname{Im})` part of :math:`\text{out}_i` as
    
    .. math::
        \operatorname{Re}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2}),\quad
        \operatorname{Im}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2})
    
    The shap

3. Jupyter 里更方便：用 ?

    在 Notebook 里可以直接写：

        如

In [74]:
torch.randn?

Docstring:
randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor


Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal
distribution).

.. math::
    \text{out}_{i} \sim \mathcal{N}(0, 1)

For complex dtypes, the tensor is i.i.d. sampled from a `complex normal distribution`_ with zero mean and
unit variance as

.. math::
    \text{out}_{i} \sim \mathcal{CN}(0, 1)

This is equivalent to separately sampling the real :math:`(\operatorname{Re})` and imaginary
:math:`(\operatorname{Im})` part of :math:`\text{out}_i` as

.. math::
    \operatorname{Re}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2}),\quad
    \operatorname{Im}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2})

The shape of the tensor is defined by the variable argument :attr:`size`.


Args:
    size (int...): a sequence of integers defining the shape of the outp

4. 查随机数函数

    PyTorch 里常见随机数函数有这些：


    torch.rand(2, 3)      # 0 到 1 的均匀分布随机数

    torch.randn(2, 3)     # 标准正态分布随机数

    torch.randint(0, 10, (2, 3))  # 0 到 9 的随机整数

In [ ]:
help(torch.rand)
help(torch.randn)
help(torch.randint)

* 最核心一句：

    函数不用死背，先会查。dir() 看有什么，help() 看怎么用。



# 2.深度学习基础

## 2.1线性回归

### 2.1.1线性回归基本要素

* 0. 先理解：什么是前向？什么是后向


      0.1前向传播就是：

         把输入数据丢进模型，算出预测值，再算出损失。

         在线性回归里：

            y_hat = X @ w + b

            loss = squared_loss(y_hat, y)

          所以前向传播做三件事：

            输入 X
            ↓
            模型算预测值 ŷ
            ↓
            损失函数算 loss



      0.2 后向传播就是：

         从损失 loss 出发，反过来计算每个参数对 loss 的影响，也就是梯度。

         在 PyTorch 里就是：

            loss.backward()


      0.3 一句话：

             前向传播：从输入到损失。

             后向传播：从损失反推梯度。